#!/bin/bash

# Exit on error
set -e

rm -f kauma

# Create and enter build directory
mkdir -p building
cd building

# Configure and build
make -j4

# Create symlink to executable
cd ..
ln -sf building/KryptoCpp kauma

echo "Build complete! You can run ./kauma"